'use strict';
// Muha exports and serves exactly these four frontend files. Keep optional
// assistant modules inside the compiled assets; do not widen the server allowlist.
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const read = name => fs.readFileSync(path.join(root, name), 'utf8').replace(/\r\n/g, '\n').trimEnd();
function assets() {
  return {
    'app.js': '// Generated by node frontend/build.cjs. Edit app-source.js / agent*.js.\n' +
      ['agent.js', 'agent-ui.js', 'app-source.js'].map(read).join('\n;\n') + '\n',
    'styles.css': '/* Generated by node frontend/build.cjs. Edit styles-source.css / agent.css. */\n' +
      ['styles-source.css', 'agent.css'].map(read).join('\n\n') + '\n'
  };
}
if (require.main === module) {
  const check = process.argv.includes('--check');
  for (const [name, content] of Object.entries(assets())) {
    if (check) {
      if (read(name) !== content.trimEnd()) throw new Error(name + ' is stale: run node frontend/build.cjs');
    } else fs.writeFileSync(path.join(root, name), content, 'utf8');
  }
  console.log(check ? 'Frontend bundles are current.' : 'Built Muha-compatible app.js and styles.css.');
}
module.exports = { assets };
